### ISSUE TITLE
Unable to deposit UST：Expected private key to be an Uint8Array

### ISSUE THREAD

**Issue by FlagDied** [stationmoney/station#46]
I'm trying to deposit UST into Anchor, however I keep getting an error saying：
“Expected private key to be an Uint8Array with length 32”
I think it maybe a problem about encoding,but i do not know how to solve it.
 I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this. 
error detail：
Error type: CreateTxFailed
Error stack: CreateTxFailed: Expected private key to be an Uint8Array with length 32
    at mapExtensionTxError (https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:24355)
    at Object.error (https://app.anchorprotocol.com/assets/main.e0f08b50.js:59:108994)
    at Object.error (https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:9090)
    at t._error (https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:8290)
    at t.error (https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:7958)
    at https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:12829
    at errorContext (https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:7576)
    at t.error (https://app.anchorprotocol.com/assets/main.e0f08b50.js:42:12684)
    at https://app.anchorprotocol.com/assets/main.e0f08b50.js:59:82976

**Comment by simcheolhwan** [comment]
Restore your wallet with mnemonic and try again.
If you need more help, send a message to @simcheolhwan on Telegram.
